package cloud.autotests.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.*;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class AppTests extends TestBase {
    @Test
    @Description("Soon to be implemented by QA.GURU engineers")
    @DisplayName("Aerokube some test")
    void generatedTest() {
        step("open https://aerokube.com/", () -> {
            // todo
        });

        step("scroll to", () -> {
            // todo
        });

        step("any action", () -> {
            // todo
        });
    }

    @Test
    @Description("Autogenerated, because your test steps contain text 'http...' and the page has &lt;title&gt;")
    @DisplayName("Page title test")
    void titleTest() {
        step("Open url 'https://aerokube.com/'", () ->
            open("https://aerokube.com/"));

        step("Checking that the page title has is 'Aerokube | Efficient Selenium Testing Infrastructure'", () -> {
            String expectedTitle = "Aerokube | Efficient Selenium Testing Infrastructure";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}